services:
  mariadb:
    image: mariadb
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
      timeout: 3s
      retries: 5
    restart: always
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception_network

  wordpress:
    image: wordpress
    build:
      context: ./requirements/wordpress
    container_name: wordpress
    depends_on:
      mariadb:
        condition: service_healthy
    restart: always
    env_file:
      - .env
    # ports:
    #   - "9000:9000"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception_network

  nginx:
    image: nginx
    build:
      context: ./requirements/nginx
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
      - ./requirements/nginx/conf:/etc/nginx/conf.d
      - ./secrets:/etc/nginx/ssl
    networks:
      - inception_network
    depends_on:
      - wordpress

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/mariadb
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/wordpress

networks:
  inception_network:
    driver: bridge
