services:
  mariadb:
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - type: bind
        source: ${HOME}/data/mariadb
        target: /var/lib/mysql
        read_only: false
    networks:
      - inception_network

  # wordpress:
  #   build:
  #     context: ./requirements/wordpress
  #   container_name: wordpress
  #   depends_on:
  #     - mariadb
  #   restart: always
  #   env_file:
  #     - .env
  #   volumes:
  #     - wordpress_data:/var/www/html
  #   networks:
  #     - inception_network

  nginx:
    build:
      context: ./requirements/nginx
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - ./requirements/nginx/conf:/etc/nginx/conf.d
      - ./secrets:/etc/nginx/ssl
    networks:
      - inception_network

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/mariadb
  # wordpress_data:
  #   driver: local
  #   driver_opts:
  #     type: none
  #     o: bind
  #     device: ${HOME}/data/wordpress

networks:
  inception_network:
    driver: bridge
